#name: C/C++ CI

#on:
#  push:
 #   branches: [ "main" ]
  #pull_request:
   # branches: [ "main" ]

#jobs:
# build:

#    runs-on: ubuntu-latest

#    steps:
#    - uses: actions/checkout@v4
#    - name: configure
#     run: ./configure
#   - name: make
#     run: make
#   - name: make check
#    run: make check
#   - name: make distcheck
#     run: make distcheck
name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    #strategy:
    #matrix:
     #   python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    #- name: Set up Python
     # uses: actions/setup-python@v2
     # with:
      #  python-version: ${{ matrix.python-version }}

    #- name: Install dependencies
     # run: |
     #   python -m pip install --upgrade pip
      #  pip install pytest

    - name: Build Code
      run: |
        cd src
        g++ Test.cpp
